### ISSUE TITLE
运行 cyber_channel list 结果不对 怎么回事

### ISSUE THREAD

**Issue by panxiaobao** [minhanghuang/CyberRT#14]
pxb@pxb-Lenovo:/ssd/pxb/code/SWE-1.0/CyberRT/build$ cyber_channel list
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0307 18:49:05.804024  5432 class_loader_utility.h:79] []registerclass:Circle,Base,
I0307 18:49:05.804076  5432 class_loader_utility.h:79] []registerclass:Rect,Base,
I0307 18:49:05.804085  5432 class_loader_utility.h:79] []registerclass:Triangle,Base,
I0307 18:49:05.804090  5432 class_loader_utility.h:79] []registerclass:Star,Base,
I0307 18:49:05.804097  5432 class_loader_utility.h:79] []registerclass:Apple,Base,
I0307 18:49:05.804103  5432 class_loader_utility.h:79] []registerclass:Pear,Base,
I0307 18:49:05.804108  5432 class_loader_utility.h:79] []registerclass:Banana,Base,
I0307 18:49:05.804114  5432 class_loader_utility.h:79] []registerclass:Peach,Base,
I0307 18:49:05.947216  5432 global_data.cc:153] [cyber_py]host ip: 10.10.1.59
W0307 18:49:05.947680  5432 scheduler_factory.cc:63] [cyber_py]Scheduler conf named /ssd/pxb/code/SWE-1.0/CyberRT/build/share/conf/python3.6_5432.conf not found, use default.
I0307 18:49:05.947868  5435 processor.cc:42] [cyber_py]processor_tid: 5435
I0307 18:49:05.947942  5436 processor.cc:42] [cyber_py]processor_tid: 5436
I0307 18:49:05.948025  5437 processor.cc:42] [cyber_py]processor_tid: 5437
I0307 18:49:05.948139  5438 processor.cc:42] [cyber_py]processor_tid: 5438
I0307 18:49:05.948195  5439 processor.cc:42] [cyber_py]processor_tid: 5439
I0307 18:49:05.948314  5440 processor.cc:42] [cyber_py]processor_tid: 5440
I0307 18:49:05.948341  5441 processor.cc:42] [cyber_py]processor_tid: 5441
I0307 18:49:05.948436  5442 processor.cc:42] [cyber_py]processor_tid: 5442
I0307 18:49:05.948498  5443 processor.cc:42] [cyber_py]processor_tid: 5443
I0307 18:49:05.948520  5444 processor.cc:42] [cyber_py]processor_tid: 5444
I0307 18:49:05.948556  5445 processor.cc:42] [cyber_py]processor_tid: 5445
I0307 18:49:05.948591  5446 processor.cc:42] [cyber_py]processor_tid: 5446
I0307 18:49:05.948621  5447 processor.cc:42] [cyber_py]processor_tid: 5447
I0307 18:49:05.948650  5448 processor.cc:42] [cyber_py]processor_tid: 5448
I0307 18:49:05.948676  5449 processor.cc:42] [cyber_py]processor_tid: 5449
W0307 18:49:05.948700  5432 environment.h:33] [cyber_py]Environment variable [sysmo_start] not set, fallback to 
I0307 18:49:05.948701  5450 processor.cc:42] [cyber_py]processor_tid: 5450
I0307 18:49:05.948716  5432 init.cc:113] [cyber_py]Register exit handle succ.
I0307 18:49:05.948729  5432 py_cyber.h:58] [cyber_py]cyber init succ.
The number of channels is:  0

**Comment by minhanghuang** [comment]
![image](https://user-images.githubusercontent.com/37317982/223463382-80ec8f4a-092f-479e-9a00-0a85975d41c6.png)
上图是我在本地运行的结果。
你说的结果不对是指什么?

**Comment by panxiaobao** [comment]
是本地运行的结果，你的案例不是应该出现1才对啊 我没有出现

**Comment by panxiaobao** [comment]
刚开始我在运行cmake 的时候  make 时候出现CPython 模块的错误，我考虑到Cmakelist可能没有切换到python3.6m所有稍微改了下Cmake list  然后编译成功了，但是每次运行案例时会有两处警告我怀疑和这两处警告有关

**Comment by minhanghuang** [comment]
> 

你的案例显示0个channels,  你在本地有运行节点吗? 试试另起终端运行一个点`./cyber/examples/cyber_example_talker`

**Comment by panxiaobao** [comment]
cmake_minimum_required(VERSION 3.5.1)

project(cyber VERSION 8.0.0) # Apollo Version


SET(Python3_INCLUDE_DIRS "/usr/include/python3.6m")
SET(Python3_LIBRARIES "/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so")
SET( PYTHON_EXECUTABLE /usr/bin/python3.6)

set(CMAKE_CXX_STANDARD 14)
set(TARGET_NAME ${PROJECT_NAME})
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

enable_language(ASM)

include(CMakePackageConfigHelpers)
include(GNUInstallDirs)



set(CROUTINE_FILE "cyber/croutine/detail/swap_x86_64.S")
if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
  set(CROUTINE_FILE "cyber/croutine/detail/swap_x86_64.S")
  message("### SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR} ${CROUTINE_FILE}")
else()
  set(CROUTINE_FILE "cyber/croutine/detail/swap_aarch64.S")
  message("### SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR} ${CROUTINE_FILE}")
endif(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")

find_package(Threads REQUIRED)
find_package(PkgConfig REQUIRED)
find_package(fastrtps REQUIRED)
find_package(fastcdr REQUIRED)
find_package(Poco REQUIRED COMPONENTS Foundation)
find_package(glog REQUIRED)
find_package(Protobuf REQUIRED)
# find_package(python3 REQUIRED COMPONENTS Interpreter Development)
pkg_check_modules(Gflags REQUIRED gflags)
pkg_check_modules(NlohmannJson REQUIRED nlohmann_json)

# set(Python_VERSION "${Python_VERSION_MAJOR}.${Python_VERSION_MINOR}")
set(Python_VERSION "3.6")
message("${Python_VERSION}")
set(CYBER_PYTHON_PATH "lib/python${Python_VERSION}/site-packages/cyber/python")
set(CYBER_PYTHON_INTERNAL_PATH "${CYBER_PYTHON_PATH}/internal")
set(CYBER_PYTHON_PROTOBUF_PATH "lib/python${Python_VERSION}/site-packages/cyber/proto")
set(CYBER_PYTHON_LIB "/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so")

include_directories(
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${fastcdr_INCLUDE_DIR}
    ${fastrtps_INCLUDE_DIR}
    ${Protobuf_INCLUDE_DIRS}
    ${Python3_INCLUDE_DIRS}
    ${Glog_INCLUDE_DIRS}
    ${Gflags_INCLUDE_DIRS}
    ${NlohmannJson_INCLUDE_DIRS}
)

link_directories(
    ${fastcdr_LIB_DIR}
    ${fastrtps_LIB_DIR}
    ${Protobuf_LIBRARIES_DIRS}
    # ${Python_LIBRARIES_DIRS}
    ${Glog_LIBRARY_DIRS}
    ${Gflags_LIBRARY_DIRS}
    ${NlohmannJson_LIBRARY_DIRS}
)

file(GLOB CYBER_SRCS
    "cyber/base/*.cc"
    "cyber/blocker/*.cc"
    "cyber/class_loader/*.cc"
    "cyber/class_loader/*/*.cc"
    "cyber/common/*.cc" 
    "cyber/component/*.cc"
    "cyber/croutine/*.cc"
    "cyber/croutine/*/*.cc"
    "cyber/data/*.cc"
    "cyber/event/*.cc"
    "cyber/io/*.cc"
    "cyber/logger/*.cc"
    "cyber/message/*.cc"
    "cyber/node/*.cc"
    "cyber/parameter/*.cc"
    "cyber/record/*.cc"
    "cyber/record/*/*.cc"
    "cyber/scheduler/*.cc"
    "cyber/scheduler/*/*.cc"
    "cyber/service/*.cc"
    "cyber/service_discovery/*.cc"
    "cyber/service_discovery/*/*.cc"
    "cyber/task/*.cc" 
    "cyber/time/*.cc"
    "cyber/timer/*.cc"
    "cyber/transport/*.cc"
    "cyber/transport/*/*.cc"
    "cyber/*.cc"
    "cyber/sysmo/*.cc"
    ${CROUTINE_FILE}
)

file(GLOB CYBER_PROTO_FILES
  "${CMAKE_CURRENT_SOURCE_DIR}/modules/common_msgs/*/*.proto"
  "${CMAKE_CURRENT_SOURCE_DIR}/cyber/proto/*.proto"
  "${CMAKE_CURRENT_SOURCE_DIR}/cyber/examples/proto/*.proto"
)

SET(PROTO_META_BASE_DIR ${CMAKE_CURRENT_BINARY_DIR})

LIST(APPEND PROTO_FLAGS
 -I${CMAKE_CURRENT_SOURCE_DIR}
)

FOREACH(FIL ${CYBER_PROTO_FILES})
  GET_FILENAME_COMPONENT(FIL_WE ${FIL} NAME_WE)
  string(REGEX REPLACE ".+/(.+)\\..*" "\\1" FILE_NAME ${FIL})
  string(REGEX REPLACE "(.+)\\${FILE_NAME}.*" "\\1" FILE_PATH ${FIL})
  string(REGEX MATCH "(/modules/common_msgs.*|/cyber/proto/.*|/cyber/examples/proto/.*)" OUT_PATH ${FILE_PATH})
  set(PROTO_SRCS "${CMAKE_CURRENT_BINARY_DIR}${OUT_PATH}${FIL_WE}.pb.cc")
  set(PROTO_HDRS "${CMAKE_CURRENT_BINARY_DIR}${OUT_PATH}${FIL_WE}.pb.h")
  EXECUTE_PROCESS(
    COMMAND ${PROTOBUF_PROTOC_EXECUTABLE} ${PROTO_FLAGS} --cpp_out=${PROTO_META_BASE_DIR} ${FIL}
  )
  file(COPY ${PROTO_SRCS} DESTINATION ${FILE_PATH})
  file(COPY ${PROTO_HDRS} DESTINATION ${FILE_PATH})
  LIST(APPEND ALL_PROTO_SRCS ${PROTO_SRCS})
  LIST(APPEND ALL_PROTO_HDRS ${PROTO_HDRS})
ENDFOREACH()

list(FILTER CYBER_SRCS EXCLUDE REGEX .*test[.]cc)

add_library(${TARGET_NAME} SHARED
    ${ALL_PROTO_HDRS}
    ${ALL_PROTO_SRCS}
    ${CYBER_SRCS}
)

target_link_libraries(${TARGET_NAME}
    ${Glog_LIBRARIES}
    ${Gflags_LIBRARIES}
    ${NlohmannJson_LIBRARIES}
    ${Protobuf_LIBRARIES}
    ${Poco_LIBRARIES}
    glog
    fastrtps
    fastcdr
    atomic
    uuid
)

add_executable(mainboard
  cyber/mainboard/mainboard.cc
  cyber/mainboard/module_argument.cc
  cyber/mainboard/module_controller.cc
)

target_link_libraries(mainboard
    ${TARGET_NAME}
    pthread
    ${Python3_LIBRARIES}
)
set_target_properties(mainboard PROPERTIES RUNTIME_OUTPUT_DIRECTORY "bin/")

add_subdirectory(cyber/examples)
add_subdirectory(cyber/python)
add_subdirectory(cyber/tools)
# --------------------------------------------------------------
#                      CPack
# --------------------------------------------------------------
# 打包方式
include(InstallRequiredSystemLibraries)
if (APPLE)
elseif (UNIX)
  set (CPACK_GENERATOR        "DEB")
  set (CPACK_SOURCE_GENERATOR "TGZ;ZIP")
endif ()

# system/architecture
if (WINDOWS)
  if (CMAKE_CL_64)
    set (CPACK_SYSTEM_NAME "win64")
  else ()
    set (CPACK_SYSTEM_NAME "win32")
  endif ()
  set (CPACK_PACKAGE_ARCHITECTURE)
elseif (APPLE)
  set (CPACK_PACKAGE_ARCHITECTURE "darwin")
else ()
  string (TOLOWER "${CMAKE_SYSTEM_NAME}" CPACK_SYSTEM_NAME)
  if (CMAKE_CXX_FLAGS MATCHES "-m32")
    set (CPACK_PACKAGE_ARCHITECTURE i386)
  else ()
    execute_process (
      COMMAND         dpkg --print-architecture
      RESULT_VARIABLE RV
      OUTPUT_VARIABLE CPACK_PACKAGE_ARCHITECTURE
      )
    if (RV EQUAL 0)
          string (STRIP "${CPACK_PACKAGE_ARCHITECTURE}" CPACK_PACKAGE_ARCHITECTURE)
    else ()
      execute_process (COMMAND uname -m OUTPUT_VARIABLE CPACK_PACKAGE_ARCHITECTURE)
      if (CPACK_PACKAGE_ARCHITECTURE MATCHES "x86_64")
            set (CPACK_PACKAGE_ARCHITECTURE amd64)
      else ()
        set (CPACK_PACKAGE_ARCHITECTURE i386)
      endif ()
    endif ()
  endif ()
endif ()

set(CPACK_PACKAGE_NAME   "${TARGET_NAME}")
set(CPACK_PACKAGE_CONTACT "job@minhang.me")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Apollo CyberRT")
set(CPACK_INSTALL_PREFIX              "${CMAKE_INSTALL_PREFIX}")
set(CPACK_OUTPUT_FILE_PREFIX          "packages")
set(CPACK_PACKAGE_RELOCATABLE         TRUE)
set(CPACK_MONOLITHIC_INSTALL          TRUE)
set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
set(CPACK_RPM_PACKAGE_GROUP "Development/Libraries")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/minhanghuang/CyberRT")
set(CPACK_PACKAGE_FILE_NAME   "lib${CPACK_PACKAGE_NAME}")
set(CPACK_PACKAGE_FILE_NAME   "${CPACK_PACKAGE_FILE_NAME}_${CPACK_PACKAGE_VERSION}_${CPACK_PACKAGE_ARCHITECTURE}")

include(CPack)
# --------------------------------------------------------------
#                       package 
# --------------------------------------------------------------
configure_file("cmake/${TARGET_NAME}.pc.in"
  "${PROJECT_BINARY_DIR}/pkgconfig/${TARGET_NAME}.pc" @ONLY)

configure_package_config_file(
  "${CMAKE_CURRENT_SOURCE_DIR}/cmake/${TARGET_NAME}-config.cmake.in"
  "cmake/${TARGET_NAME}-config.cmake"
  INSTALL_DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${TARGET_NAME}"
  NO_CHECK_REQUIRED_COMPONENTS_MACRO
  PATH_VARS CMAKE_INSTALL_INCLUDEDIR CMAKE_INSTALL_LIBDIR TARGET_NAME
)

write_basic_package_version_file(cmake/${TARGET_NAME}-config-version.cmake
  VERSION ${PROJECT_VERSION}
  COMPATIBILITY AnyNewerVersion
)

install(FILES
  "${PROJECT_BINARY_DIR}/pkgconfig/${TARGET_NAME}.pc"
  DESTINATION "${CMAKE_INSTALL_DATADIR}/pkgconfig"
)

install(FILES
  "${PROJECT_BINARY_DIR}/cmake/${TARGET_NAME}-config.cmake"
  "${PROJECT_BINARY_DIR}/cmake/${TARGET_NAME}-config-version.cmake"
  DESTINATION "${CMAKE_INSTALL_DATADIR}/cmake/${TARGET_NAME}"
)

install(EXPORT ${TARGET_NAME}-targets
  DESTINATION "${CMAKE_INSTALL_DATADIR}/cmake/${TARGET_NAME}"
)

# cyber .h files
install(DIRECTORY cyber/
    DESTINATION include/cyber/
    FILES_MATCHING
    PATTERN "*.h"
)

# apollo conf
file(COPY cyber/conf/
  DESTINATION ${CMAKE_BINARY_DIR}/share/conf/
)
install(DIRECTORY ${CMAKE_BINARY_DIR}/share/conf/ 
  DESTINATION share/conf/
)

# setup.zsh
file(COPY setup.zsh setup.bash
  DESTINATION ${CMAKE_BINARY_DIR}
)
install(FILES ${CMAKE_BINARY_DIR}/setup.zsh ${CMAKE_BINARY_DIR}/setup.bash
  DESTINATION .
)

# cyber python api
file(COPY cyber/python/
  DESTINATION ${CMAKE_BINARY_DIR}/${CYBER_PYTHON_PATH}
)
install(DIRECTORY ${CMAKE_BINARY_DIR}/${CYBER_PYTHON_PATH}/
  DESTINATION ${CYBER_PYTHON_PATH}
  FILES_MATCHING
  PATTERN "*.py"
)

# cyber python protobuf
file(WRITE ${CMAKE_BINARY_DIR}/${CYBER_PYTHON_PROTOBUF_PATH}/__init__.py "import os\n")
file(APPEND ${CMAKE_BINARY_DIR}/${CYBER_PYTHON_PROTOBUF_PATH}/__init__.py "import sys\n")
file(APPEND ${CMAKE_BINARY_DIR}/${CYBER_PYTHON_PROTOBUF_PATH}/__init__.py "sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))\n")
file(COPY cyber/proto/
  DESTINATION ${CMAKE_BINARY_DIR}/${CYBER_PYTHON_PROTOBUF_PATH}
  FILES_MATCHING
  PATTERN "*.py"
)

install(DIRECTORY ${CMAKE_BINARY_DIR}/${CYBER_PYTHON_PROTOBUF_PATH}/
  DESTINATION ${CYBER_PYTHON_PROTOBUF_PATH}
)

# install
install(TARGETS ${TARGET_NAME} mainboard
    EXPORT ${TARGET_NAME}-targets
    ARCHIVE DESTINATION lib
    LIBRARY DESTINATION lib
    RUNTIME DESTINATION bin
)

**Comment by panxiaobao** [comment]
这是我修改的  我试试你说的

**Comment by panxiaobao** [comment]
这是我运行的结果，能运行 应该还是有些问题，应该和我的pyhon 环境有关 之前find_package(python3 REQUIRED COMPONENTS Interpreter Development) 这就话老是过不了 而且我有特别希望切换到pyhon3.6 所有乱改了   晚上打扰了.

**Comment by panxiaobao** [comment]
我这边连编译也编不过了，我的原因应该是同时安装2.7和3.6环境 我ubuntu18.04 还安装了ros 所以导致在用#include<Python.h>时出现了错误 我在看看怎么解决

**Comment by minhanghuang** [comment]
> 我这边连编译也编不过了，我的原因应该是同时安装2.7和3.6环境 我ubuntu18.04 还安装了ros 所以导致在用#include<Python.h>时出现了错误 我在看看怎么解决

报什么错?  发出来看看
我的环境是docker Ubuntu 18 和 20 装了 ros 和 ros2

**Comment by panxiaobao** [comment]
没有了 消息刷没有了  就是#include<Python.h>找不到

**Comment by panxiaobao** [comment]
我明白了，我没有在docker中编译运行而是在系统环境下操作的  你的docker 镜像能发我下吗

**Comment by minhanghuang** [comment]
> 没有了 消息刷没有了 就是#include<Python.h>找不到

# Ubuntu18 : sudo apt install python3.6-dev
# Ubuntu20 : sudo apt install python3.9-dev

**Comment by panxiaobao** [comment]
这个我装个，但是我这个库找不到原因应该是它找的是Python.h找的是python2.7 而我的库链接是Python3.6  我还是在docker中运行吧  谢谢了
