### ISSUE TITLE
is there any guide for building CyberRT for Android System

### ISSUE THREAD

**Issue by FranzKafkaYu** [minhanghuang/CyberRT#19]
Hello,Is there any guide for build CyberRT  used in Android System?

I am not familiar wiht CMAKE.

Thanks in advance~

**Comment by minhanghuang** [comment]
> Hello,Is there any guide for build CyberRT used in Android System?
> 
> I am not familiar wiht CMAKE.
> 
> Thanks in advance~

Hi @FranzKafkaYu , I do not have an Android System  environment locally and have not compiled on Android. I think that the compilation of different systems mainly depends on the coroutines code of CyberRT [CyberRT-Co](https://github.com/minhanghuang/CyberRT/blob/v8.0.0/cyber/croutine/detail/swap_aarch64.S). If that part of the coroutines code can be compiled on Android System, it can be compiled according to the documentation steps.

**Comment by FranzKafkaYu** [comment]
> > Hello,Is there any guide for build CyberRT used in Android System?
> > I am not familiar wiht CMAKE.
> > Thanks in advance~
> 
> Hi @FranzKafkaYu , I do not have an Android System environment locally and have not compiled on Android. I think that the compilation of different systems mainly depends on the coroutines code of CyberRT [CyberRT-Co](https://github.com/minhanghuang/CyberRT/blob/v8.0.0/cyber/croutine/detail/swap_aarch64.S). If that part of the coroutines code can be compiled on Android System, it can be compiled according to the documentation steps.

Thanks for your reply,so I guess I  have to figure it out by myself.It seems that there are not enough guides about how can we use CybertRT,Can you recomend some tutorials for me?

**Comment by minhanghuang** [comment]
> > > Hello,Is there any guide for build CyberRT used in Android System?
> > > I am not familiar wiht CMAKE.
> > > Thanks in advance~
> > 
> > 
> > Hi @FranzKafkaYu , I do not have an Android System environment locally and have not compiled on Android. I think that the compilation of different systems mainly depends on the coroutines code of CyberRT [CyberRT-Co](https://github.com/minhanghuang/CyberRT/blob/v8.0.0/cyber/croutine/detail/swap_aarch64.S). If that part of the coroutines code can be compiled on Android System, it can be compiled according to the documentation steps.
> 
> Thanks for your reply,so I guess I have to figure it out by myself.It seems that there are not enough guides about how can we use CybertRT,Can you recomend some tutorials for me?

This article [cyber](https://github.com/daohu527/dig-into-apollo/tree/main/cyber) is a good choice

**Comment by FranzKafkaYu** [comment]
> > > > Hello,Is there any guide for build CyberRT used in Android System?
> > > > I am not familiar wiht CMAKE.
> > > > Thanks in advance~
> > > 
> > > 
> > > Hi @FranzKafkaYu , I do not have an Android System environment locally and have not compiled on Android. I think that the compilation of different systems mainly depends on the coroutines code of CyberRT [CyberRT-Co](https://github.com/minhanghuang/CyberRT/blob/v8.0.0/cyber/croutine/detail/swap_aarch64.S). If that part of the coroutines code can be compiled on Android System, it can be compiled according to the documentation steps.
> > 
> > 
> > Thanks for your reply,so I guess I have to figure it out by myself.It seems that there are not enough guides about how can we use CybertRT,Can you recomend some tutorials for me?
> 
> This article [cyber](https://github.com/daohu527/dig-into-apollo/tree/main/cyber) is a good choice

thank you very much!
