### ISSUE TITLE
fastrtps dependency

### ISSUE THREAD

**Issue by yongjay** [minhanghuang/CyberRT#20]
hi ,
scripts/install.sh :
```

if [[ "${ARCH}" == "x86_64" ]]; then
    PKG_NAME="fast-rtps-1.5.0-1.prebuilt.x86_64.tar.gz"
  else # aarch64
    PKG_NAME="fast-rtps-1.5.0-1.prebuilt.aarch64.tar.gz"
  fi
  DOWNLOAD_LINK="https://apollo-system.cdn.bcebos.com/archive/6.0/${PKG_NAME}"
  if [ -e $INSTALL_PATH/$PKG_NAME ]
  then
    echo ""
  else
    wget $DOWNLOAD_LINK -P $INSTALL_PATH
  fi
```

1.  I notice that fastrtps is a prebuild version, is it because of any special changes?
2. If I want to cross-compile CyberRT to another platform, should I download the source code of fastrtps-1.5.0 and recompile with my cross-compile toochain？

look forward to your reply!

**Comment by minhanghuang** [comment]
> hi , scripts/install.sh :
> 
> ```
> 
> if [[ "${ARCH}" == "x86_64" ]]; then
>     PKG_NAME="fast-rtps-1.5.0-1.prebuilt.x86_64.tar.gz"
>   else # aarch64
>     PKG_NAME="fast-rtps-1.5.0-1.prebuilt.aarch64.tar.gz"
>   fi
>   DOWNLOAD_LINK="https://apollo-system.cdn.bcebos.com/archive/6.0/${PKG_NAME}"
>   if [ -e $INSTALL_PATH/$PKG_NAME ]
>   then
>     echo ""
>   else
>     wget $DOWNLOAD_LINK -P $INSTALL_PATH
>   fi
> ```
> 
> 1. I notice that fastrtps is a prebuild version, is it because of any special changes?
> 2. If I want to cross-compile CyberRT to another platform, should I download the source code of fastrtps-1.5.0 and recompile with my cross-compile toochain？
> 
> look forward to your reply!

yep, `fast-dds1.5.0` version requires [patching](https://github.com/ApolloAuto/apollo-platform/blob/master/ros/third_party/FastRTPS_1.4.0.patch), whether or not you need to recompile depends on the architecture of your platform, and recompile is not a problem as long as you add patch files during compilation,

**Comment by yongjay** [comment]
> > hi , scripts/install.sh :
> > ```
> > 
> > if [[ "${ARCH}" == "x86_64" ]]; then
> >     PKG_NAME="fast-rtps-1.5.0-1.prebuilt.x86_64.tar.gz"
> >   else # aarch64
> >     PKG_NAME="fast-rtps-1.5.0-1.prebuilt.aarch64.tar.gz"
> >   fi
> >   DOWNLOAD_LINK="https://apollo-system.cdn.bcebos.com/archive/6.0/${PKG_NAME}"
> >   if [ -e $INSTALL_PATH/$PKG_NAME ]
> >   then
> >     echo ""
> >   else
> >     wget $DOWNLOAD_LINK -P $INSTALL_PATH
> >   fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. I notice that fastrtps is a prebuild version, is it because of any special changes?
> > 2. If I want to cross-compile CyberRT to another platform, should I download the source code of fastrtps-1.5.0 and recompile with my cross-compile toochain？
> > 
> > look forward to your reply!
> 
> yep, `fast-dds1.5.0` version requires [patching](https://github.com/ApolloAuto/apollo-platform/blob/master/ros/third_party/FastRTPS_1.4.0.patch), whether or not you need to recompile depends on the architecture of your platform, and recompile is not a problem as long as you add patch files during compilation,

Thanks a lot , I added [patching](https://github.com/ApolloAuto/apollo-platform/blob/master/ros/third_party/FastRTPS_1.4.0.patch) and recompiled fastrtps1.5.0 ,it works. So If anyone else needs to cross-compile like me, they'd better do it or they might have some link issues when compiling cyberRT at the end.

**Comment by i-Nog** [comment]
> > > hi , scripts/install.sh :
> > > ```
> > > 
> > > if [[ "${ARCH}" == "x86_64" ]]; then
> > >     PKG_NAME="fast-rtps-1.5.0-1.prebuilt.x86_64.tar.gz"
> > >   else # aarch64
> > >     PKG_NAME="fast-rtps-1.5.0-1.prebuilt.aarch64.tar.gz"
> > >   fi
> > >   DOWNLOAD_LINK="https://apollo-system.cdn.bcebos.com/archive/6.0/${PKG_NAME}"
> > >   if [ -e $INSTALL_PATH/$PKG_NAME ]
> > >   then
> > >     echo ""
> > >   else
> > >     wget $DOWNLOAD_LINK -P $INSTALL_PATH
> > >   fi
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 1. I notice that fastrtps is a prebuild version, is it because of any special changes?
> > > 2. If I want to cross-compile CyberRT to another platform, should I download the source code of fastrtps-1.5.0 and recompile with my cross-compile toochain？
> > > 
> > > look forward to your reply!
> > 
> > 
> > yep, `fast-dds1.5.0` version requires [patching](https://github.com/ApolloAuto/apollo-platform/blob/master/ros/third_party/FastRTPS_1.4.0.patch), whether or not you need to recompile depends on the architecture of your platform, and recompile is not a problem as long as you add patch files during compilation,
> 
> Thanks a lot , I added [patching](https://github.com/ApolloAuto/apollo-platform/blob/master/ros/third_party/FastRTPS_1.4.0.patch) and recompiled fastrtps1.5.0 ,it works. So If anyone else needs to cross-compile like me, they'd better do it or they might have some link issues when compiling cyberRT at the end.

I did cross-compile like you, but there is an error. Do u know how to fix it? @minhanghuang Do U have an idea for this?
```bash
/usr/bin/ld: /workspace/thirdparty/Fast-DDS-1.5.0/build-rk356x/src/cpp/libfastrtps.so.1.5.0: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[5]: *** [CMakeFiles/UseCaseSubscriber.dir/build.make:116: UseCaseSubscriber] Error 1
make[4]: *** [CMakeFiles/Makefile2:78: CMakeFiles/UseCaseSubscriber.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [examples/CMakeFiles/Configurability.dir/build.make:112: examples/Configurability-prefix/src/Configurability-stamp/Configurability-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:1576: examples/CMakeFiles/Configurability.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Building CXX object CMakeFiles/FlowControlExample.dir/FlowControlExampleSubscriber.cxx.o
[100%] Linking CXX executable sampleconfig_multimedia
[ 42%] Building CXX object CMakeFiles/DeadlineQoSExample.dir/deadlinepayloadPubSubMain.cxx.o
/usr/bin/ld: /workspace/thirdparty/Fast-DDS-1.5.0/build-rk356x/src/cpp/libfastrtps.so.1.5.0: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[5]: *** [CMakeFiles/sampleconfig_multimedia.dir/build.make:116: sampleconfig_multimedia] Error 1
make[4]: *** [CMakeFiles/Makefile2:76: CMakeFiles/sampleconfig_multimedia.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [examples/CMakeFiles/SampleConfig_Multimedia.dir/build.make:112: examples/SampleConfig_Multimedia-prefix/src/SampleConfig_Multimedia-stamp/SampleConfig_Multimedia-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:1603: examples/CMakeFiles/SampleConfig_Multimedia.dir/all] Error 2
```
