### ISSUE TITLE
cyber_channel list 报错

### ISSUE THREAD

**Issue by Minphie** [minhanghuang/CyberRT#25]
![image](https://github.com/minhanghuang/CyberRT/assets/16850655/e31b6437-55ba-4977-8870-136678287d8a)
您好，环境是ubuntu22.04 + python3.10，talker和listener正常运行，cyber工具运行会报错。

**Comment by minhanghuang** [comment]
hi @Minphie 我在使用Ubuntu22时复现了你描述的问题, 查了资料后发现大概是Python3.9+开始引入了一个新的规则，要求在使用某些格式标记时定义PY_SSIZE_T_CLEAN宏, 所以只需要在`#include <Python.h>`前加上`#define PY_SSIZE_T_CLEAN`即可解决该问题[https://github.com/minhanghuang/CyberRT/commit/fda46f74d96ac7af9a8251564840c2330bb39771](https://github.com/minhanghuang/CyberRT/commit/fda46f74d96ac7af9a8251564840c2330bb39771)

**Comment by Minphie** [comment]
谢谢，已经解决了。
