### ISSUE TITLE
执行最后一步 make -j$(nproc) 时出错

### ISSUE THREAD

**Issue by GaryWang778** [minhanghuang/CyberRT#29]
截取了一部分报错情况，请问可以帮忙看一下问题出在哪儿吗？
`/home/wgc/CyberRT/build/cyber/proto/cyber_conf.pb.cc: In member function ‘void apollo::cyber::proto::CyberConfig::InternalSwap(apollo::cyber::proto::CyberConfig*)’:
/home/wgc/CyberRT/build/cyber/proto/cyber_conf.pb.cc:456:23: error: ‘class google::protobuf::internal::InternalMetadata’ has no member named ‘InternalSwap’
  456 |   _internal_metadata_.InternalSwap(&other->_internal_metadata_);
      |                       ^~~~~~~~~~~~
/home/wgc/CyberRT/build/cyber/proto/cyber_conf.pb.cc: In member function ‘virtual google::protobuf::Metadata apollo::cyber::proto::CyberConfig::GetMetadata() const’:
/home/wgc/CyberRT/build/cyber/proto/cyber_conf.pb.cc:467:12: error: ‘::_pbi’ has not been declared
  467 |   return ::_pbi::AssignDescriptors(
      |            ^~~~
/home/wgc/CyberRT/build/cyber/proto/cyber_conf.pb.cc:468:8: error: ‘descriptor_table_cyber_2fproto_2fcyber_5fconf_2eproto_getter’ was not declared in this scope; did you mean ‘descriptor_table_cyber_2fproto_2fcyber_5fconf_2eproto’?
  468 |       &descriptor_table_cyber_2fproto_2fcyber_5fconf_2eproto_getter, &descriptor_table_cyber_2fproto_2fcyber_5fconf_2eproto_once,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |        descriptor_table_cyber_2fproto_2fcyber_5fconf_2eproto
/home/wgc/CyberRT/build/cyber/proto/cyber_conf.pb.cc:468:71: error: ‘descriptor_table_cyber_2fproto_2fcyber_5fconf_2eproto_once’ was not declared in this scope; did you mean ‘descriptor_table_cyber_2fproto_2fcyber_5fconf_2eproto’?
  468 |       &descriptor_table_cyber_2fproto_2fcyber_5fconf_2eproto_getter, &descriptor_table_cyber_2fproto_2fcyber_5fconf_2eproto_once,
      |                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                       descriptor_table_cyber_2fproto_2fcyber_5fconf_2eproto
/home/wgc/CyberRT/build/cyber/proto/cyber_conf.pb.cc:469:7: error: ‘file_level_metadata_cyber_2fproto_2fcyber_5fconf_2eproto’ was not declared in this scope; did you mean ‘TableStruct_cyber_2fproto_2fcyber_5fconf_2eproto’?
  469 |       file_level_metadata_cyber_2fproto_2fcyber_5fconf_2eproto[0]);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       TableStruct_cyber_2fproto_2fcyber_5fconf_2eproto
In file included from /home/wgc/CyberRT/cyber/proto/record.pb.h:24,
                 from /home/wgc/CyberRT/build/cyber/proto/record.pb.cc:4:
/usr/local/include/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = apollo::cyber::proto::SingleIndex]’:
/home/wgc/CyberRT/build/cyber/proto/record.pb.cc:3547:83:   required from here
/usr/local/include/google/protobuf/arena.h:464:14: error: invalid new-expression of abstract class type ‘apollo::cyber::proto::SingleIndex’
  464 |       return new T();
      |              ^~~~~~~
/usr/local/include/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = apollo::cyber::proto::ChunkHeaderCache]’:
/home/wgc/CyberRT/build/cyber/proto/record.pb.cc:3551:88:   required from here
/usr/local/include/google/protobuf/arena.h:464:14: error: invalid new-expression of abstract class type ‘apollo::cyber::proto::ChunkHeaderCache’
/usr/local/include/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = apollo::cyber::proto::ChunkBodyCache]’:
/home/wgc/CyberRT/build/cyber/proto/record.pb.cc:3555:86:   required from here
/usr/local/include/google/protobuf/arena.h:464:14: error: invalid new-expression of abstract class type ‘apollo::cyber::proto::ChunkBodyCache’
/usr/local/include/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = apollo::cyber::proto::ChannelCache]’:
/home/wgc/CyberRT/build/cyber/proto/record.pb.cc:3559:84:   required from here
/usr/local/include/google/protobuf/arena.h:464:14: error: invalid new-expression of abstract class type ‘apollo::cyber::proto::ChannelCache’
/usr/local/include/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = apollo::cyber::proto::SingleMessage]’:
/home/wgc/CyberRT/build/cyber/proto/record.pb.cc:3563:85:   required from here
/usr/local/include/google/protobuf/arena.h:464:14: error: invalid new-expression of abstract class type ‘apollo::cyber::proto::SingleMessage’
/usr/local/include/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = apollo::cyber::proto::Header]’:
/home/wgc/CyberRT/build/cyber/proto/record.pb.cc:3567:78:   required from here
/usr/local/include/google/protobuf/arena.h:464:14: error: invalid new-expression of abstract class type ‘apollo::cyber::proto::Header’
/usr/local/include/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = apollo::cyber::proto::Channel]’:
/home/wgc/CyberRT/build/cyber/proto/record.pb.cc:3571:79:   required from here
/usr/local/include/google/protobuf/arena.h:464:14: error: invalid new-expression of abstract class type ‘apollo::cyber::proto::Channel’
/usr/local/include/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = apollo::cyber::proto::ChunkHeader]’:
/home/wgc/CyberRT/build/cyber/proto/record.pb.cc:3575:83:   required from here
/usr/local/include/google/protobuf/arena.h:464:14: error: invalid new-expression of abstract class type ‘apollo::cyber::proto::ChunkHeader’
/usr/local/include/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = apollo::cyber::proto::ChunkBody]’:
/home/wgc/CyberRT/build/cyber/proto/record.pb.cc:3579:81:   required from here
/usr/local/include/google/protobuf/arena.h:464:14: error: invalid new-expression of abstract class type ‘apollo::cyber::proto::ChunkBody’
/usr/local/include/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = apollo::cyber::proto::Index]’:
/home/wgc/CyberRT/build/cyber/proto/record.pb.cc:3583:77:   required from here
/usr/local/include/google/protobuf/arena.h:464:14: error: invalid new-expression of abstract class type ‘apollo::cyber::proto::Index’
In file included from /home/wgc/CyberRT/cyber/proto/cyber_conf.pb.h:24,
                 from /home/wgc/CyberRT/build/cyber/proto/cyber_conf.pb.cc:4:
/usr/local/include/google/protobuf/arena.h: In instantiation of ‘static T* google::protobuf::Arena::CreateMessageInternal(google::protobuf::Arena*) [with T = apollo::cyber::proto::CyberConfig]’:
/home/wgc/CyberRT/build/cyber/proto/cyber_conf.pb.cc:479:83:   required from here
/usr/local/include/google/protobuf/arena.h:464:14: error: invalid new-expression of abstract class type ‘apollo::cyber::proto::CyberConfig’
  464 |       return new T();
      |              ^~~~~~~
make[2]: *** [CMakeFiles/cyber.dir/build.make:230：CMakeFiles/cyber.dir/cyber/proto/record.pb.cc.o] 错误 1
make[2]: *** [CMakeFiles/cyber.dir/build.make:146：CMakeFiles/cyber.dir/cyber/proto/cyber_conf.pb.cc.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:190：CMakeFiles/cyber.dir/all] 错误 2
make: *** [Makefile:156：all] 错误 2
`

**Comment by minhanghuang** [comment]
Hi @GaryWang778 请问一下,你的编译环境是什么? 直行的是哪个脚本报的错?

**Comment by GaryWang778** [comment]
经过排查，应该是protobuf版本安装的不匹配，现在已经编译通过可以正常运行，谢谢～
