### ISSUE TITLE
No module named 'cyber.python'

### ISSUE THREAD

**Issue by plumewind** [minhanghuang/CyberRT#34]
hello, test the **cyber_example_listener** and **cyber_example_listener** is ok, and **cyber_monitor** is ok, 
but get error by using the **cyber_channel list** :

```
➜  build git:(v8.0.0) source setup.zsh 
➜  build git:(v8.0.0) cyber_channel list
Traceback (most recent call last):
  File "/home/mini/researches/cyber_rt_8/CyberRT/build/bin/cyber_channel", line 23, in <module>
    from cyber.python.cyber_py3 import cyber_time
ModuleNotFoundError: No module named 'cyber.python'
```

What can I do? Thanks a lot.

**Comment by minhanghuang** [comment]
> /home/mini/researches/cyber_rt_8/CyberRT

hi @plumewind , Please check the Python version in `CyberRT/build/lib`. If it is `python 3.8`, please try running the following command: `export PYTHONPATH=$PYTHONPATH:/home/mini/researches/cyber_rt_8/CyberRT/build/lib/python3.8/site-packages`

**Comment by plumewind** [comment]
It still error.

![image](https://github.com/minhanghuang/CyberRT/assets/25976399/89c1f395-1ed4-4a3b-b903-7975a79c4570)

**Comment by plumewind** [comment]
my local environment is ubuntu20.04, should other command be setting?

**Comment by minhanghuang** [comment]
According to the error message, it appears that the `cyber/python` directory was not found in the `build/lib/python3.8/site-packages/` path. Please verify that your environment and the steps you followed are correct. Here is my local environment:
![image](https://github.com/minhanghuang/CyberRT/assets/37317982/39aa6632-f525-4ee8-9be9-eb34fd74092d)

**Comment by plumewind** [comment]
It is a unhappy thing.I want to cry for a while.

![image](https://github.com/minhanghuang/CyberRT/assets/25976399/c2fb7133-ac45-4824-8ddd-4948cf37b01b)

**Comment by minhanghuang** [comment]
> It is a unhappy thing.I want to cry for a while.
> 
> ![image](https://user-images.githubusercontent.com/25976399/250076259-c2fb7133-ac45-4824-8ddd-4948cf37b01b.png)

You can try it with a clean Docker environment.
