### ISSUE TITLE
bazel生成库，CMakeLists调用的问题

### ISSUE THREAD

**Issue by lllxiang** [minhanghuang/CyberRT#35]
楼主，请教一个问题：使用apollo 提供的bazel工具编译cyber，并生成相关so。在另外CMake工程中编译Demo并链接相关cyber的so，理论上可以吗

**Comment by minhanghuang** [comment]
> 楼主，请教一个问题：使用apollo 提供的bazel工具编译cyber，并生成相关so。在另外CMake工程中编译Demo并链接相关cyber的so，理论上可以吗

@lllxiang, 可以的  没问题, 生成的so链接路径和使用环境一致就可以
