### ISSUE TITLE
新手的疑问

### ISSUE THREAD

**Issue by GaryWang778** [minhanghuang/CyberRT#37]
大佬您好！
我编了一个使用cyberRT api的一系列代码文件，同时引用了一个本地第三方库，在编译时遇到了困难（第一次编译这种大型项目）。
观察 cyber/examples 的示例，发现示例项目既使用了Bazel Build，也使用了CmakeList.txt，想问一下该项目是用Bazel构建protobuf文件，再用Cmake构建整体项目的吗？

**Comment by minhanghuang** [comment]
> 大佬您好！ 我编了一个使用cyberRT api的一系列代码文件，同时引用了一个本地第三方库，在编译时遇到了困难（第一次编译这种大型项目）。 观察 cyber/examples 的示例，发现示例项目既使用了Bazel Build，也使用了CmakeList.txt，想问一下该项目是用Bazel构建protobuf文件，再用Cmake构建整体项目的吗？

hi, @GaryWang778 这个仓库全部使用Cmake编译, 关于Bazel的配置文件是Apollo的
