### ISSUE TITLE
*** No rule to make target '/opt/cyber/env/lib/libtinyxml2.so', needed by 'libcyber.so'.  Stop.

### ISSUE THREAD

**Issue by shelman-zl** [minhanghuang/CyberRT#4]
How can I modify the  ’/opt/cyber/env/lib/‘ path to complile the cyber?

**Comment by yanglianoo** [comment]
解决了么兄弟，同样遇到了这个问题

**Comment by minhanghuang** [comment]
> How can I modify the ’/opt/cyber/env/lib/‘ path to complile the cyber?

@shelman-zl Sorry repley you so late, The problem has been solved

**Comment by minhanghuang** [comment]
> 解决了么兄弟，同样遇到了这个问题

@yanglianoo 非常抱歉, 是我一时疏忽, 出现了这个问题, 目前已经修复
