### ISSUE TITLE
大佬好，请问是怎么构建的ARM64的环境。这边用vmware+docker+qemu拉取

### ISSUE THREAD

**Issue by yrjyrj** [minhanghuang/CyberRT#40]
这边用vmware+docker+qemu拉取的镜像，想尝试编译大佬的CbyerRT，但是遇到几个问题
1）使用sudo docker pull --platform linux/amd64 multiarch/qemu-user-static
sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
sudo docker pull arm64v8/ubuntu
sudo docker run -it --rm --name arm-container --platform linux/arm64/v8 arm64v8/ubuntu /bin/bash,可以成功编译大佬的CyberRT并在arm64v8的容器里运行
2）问题出现，在目标板上运行会提示libc.so.6,libstdc++.so版本过高。查看arm64v8的容器，发现apt源默认选择的是jammy（22.04）版本；如果apt源选择bionic（18.04），则会无法update，提示NO PUBKEY；先用默认的jammy源更新后，安装gpg，然后add key，此时再切换bionic源可以成功update，但是会提示libc6(2.27=3ubuntu1.6)等需要安装新版本2.35-0ubuntu3.1，符合目标板子的旧版本不会被安装
3）麻烦大佬给点建议，有没有18.04的arm64v8的虚拟机，能成功update出低版本的libc6的？
4）或者能否给点建议，我最开始是在x64上面交叉编译大佬的工程，但是一直编译不过，哪条路比较好走呢？谢谢

**Comment by yrjyrj** [comment]
第四点的话，交叉编译完third_party后，在CbyerRT目录下创建build，然后进入build，执行cmake -D交叉编译工具链 ..   ，然后就会提示找不到fastrtpsConfig.cmake,其他库也是一样找不到。

**Comment by yrjyrj** [comment]
> > 这边用vmware+docker+qemu拉取的镜像，想尝试编译大佬的CbyerRT，但是遇到几个问题 1）使用sudo docker pull --platform linux/amd64 multiarch/qemu-user-static sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes sudo docker pull arm64v8/ubuntu sudo docker run -it --rm --name arm-container --platform linux/arm64/v8 arm64v8/ubuntu /bin/bash,可以成功编译大佬的CyberRT并在arm64v8的容器里运行 2）问题出现，在目标板上运行会提示libc.so.6,libstdc++.so版本过高。查看arm64v8的容器，发现apt源默认选择的是jammy（22.04）版本；如果apt源选择bionic（18.04），则会无法update，提示NO PUBKEY；先用默认的jammy源更新后，安装gpg，然后add key，此时再切换bionic源可以成功update，但是会提示libc6(2.27=3ubuntu1.6)等需要安装新版本2.35-0ubuntu3.1，符合目标板子的旧版本不会被安装 3）麻烦大佬给点建议，有没有18.04的arm64v8的虚拟机，能成功update出低版本的libc6的？ 4）或者能否给点建议，我最开始是在x64上面交叉编译大佬的工程，但是一直编译不过，哪条路比较好走呢？谢谢
> 
> Hi @yrjyrj 你是想在编译机上编译CyberRT, 然后放到目标机上使用是吧? 关于镜像源的问题, 如果容器是22.04, 使用22.04的镜像源, 就不会出现update失败的问题。

感谢回复，是的，我要编译到目标机上运行CbyerRT。目前的问题就是容器是用上面的命令拉取的，它虽然是18.04/20.04，但是配置的apt源都是jammy22.04，这样就会导致目标机上运行提示libc,libstdc++版本过高。

**Comment by minhanghuang** [comment]
关于编译机和目标机, 尽量让这两个机器的Ubuntu系统版本保持一致
