### ISSUE TITLE
cyber_launch start启动common.launch时 报错

### ISSUE THREAD

**Issue by freekevinCode** [minhanghuang/CyberRT#43]
按照项目Readme文档
cyber_launch start启动common.launch时 报错
`dev@dev-virtual-machine:~/work/CyberRT-8.0.0/build$ cyber_launch start share/examples/common.launch 
[cyber_launch_89175] INFO Launch file [/home/dev/work/CyberRT-8.0.0/build/share/examples/common.launch]
[cyber_launch_89175] INFO ========================================================================================================================
[cyber_launch_89175] INFO Load module [common] library: [common] [CYBER_DEFAULT] conf: [/apollo/cyber/examples/common_component_example/common.dag] exception_handler: []
**[common ]  mainboard: error while loading shared libraries: libglog.so.0: cannot open shared object file: No such file or directory**
[cyber_launch_89175] INFO Start process [common] successfully. pid: 89177
[cyber_launch_89175] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_89175] ERROR Process [common] has died [pid 89177, exit code 127, cmd mainboard -d /apollo/cyber/examples/common_component_example/common.dag -p common -s CYBER_DEFAULT].
[cyber_launch_89175] INFO All processes has died.
[cyber_launch_89175] INFO Cyber exit.
[cyber_launch_89175] INFO All processes have been stopped.

dev@dev-virtual-machine:~/work/CyberRT-8.0.0/build$ `

**Comment by minhanghuang** [comment]
> 

Hi @freekevinCode 看日志应该是glog库没有链接对, 先确定一下你的Terminal是否有`source install/setup.bash`, 如果还是报错, 可以手动修改环境`export LD_LIBRARY_PATH=/path/to/library:$LD_LIBRARY_PATH`

**Comment by freekevinCode** [comment]
新的报错 谢谢
`dev@dev-virtual-machine:~/work/CyberRT-8.0.0/build$ source ../install/setup.bash
dev@dev-virtual-machine:~/work/CyberRT-8.0.0/build$ source setup.bash 
dev@dev-virtual-machine:~/work/CyberRT-8.0.0/build$ cyber_launch start share/examples/common.launch 
[cyber_launch_89667] INFO Launch file [/home/dev/work/CyberRT-8.0.0/build/share/examples/common.launch]
[cyber_launch_89667] INFO ========================================================================================================================
[cyber_launch_89667] INFO Load module [common] library: [common] [CYBER_DEFAULT] conf: [/apollo/cyber/examples/common_component_example/common.dag] exception_handler: []
[cyber_launch_89667] INFO Start process [common] successfully. pid: 89668
[cyber_launch_89667] INFO ------------------------------------------------------------------------------------------------------------------------
[common ]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[common ]  I0807 13:45:23.455677 89668 class_loader_utility.h:79] []registerclass:Circle,Base,
[common ]  I0807 13:45:23.456017 89668 class_loader_utility.h:79] []registerclass:Rect,Base,
[common ]  I0807 13:45:23.456054 89668 class_loader_utility.h:79] []registerclass:Triangle,Base,
[common ]  I0807 13:45:23.456099 89668 class_loader_utility.h:79] []registerclass:Star,Base,
[common ]  I0807 13:45:23.456108 89668 class_loader_utility.h:79] []registerclass:Apple,Base,
[common ]  I0807 13:45:23.456115 89668 class_loader_utility.h:79] []registerclass:Pear,Base,
[common ]  I0807 13:45:23.456120 89668 class_loader_utility.h:79] []registerclass:Banana,Base,
[common ]  I0807 13:45:23.456130 89668 class_loader_utility.h:79] []registerclass:Peach,Base,
[common ]  I0807 13:45:23.456626 89668 module_argument.cc:81] []command: mainboard -d /apollo/cyber/examples/common_component_example/common.dag -p common -s CYBER_DEFAULT 
[common ]  I0807 13:45:23.456874 89668 global_data.cc:153] []host ip: 192.168.92.133
[common ]  I0807 13:45:23.463938 89668 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is common, has 1 dag conf
[common ]  I0807 13:45:23.463974 89668 module_argument.cc:60] []dag_conf: /apollo/cyber/examples/common_component_example/common.dag
[common ]  W0807 13:45:23.464294 89668 scheduler_factory.cc:63] [mainboard]Scheduler conf named /home/dev/work/CyberRT-8.0.0/build/share/conf/common.conf not found, use default.
[common ]  I0807 13:45:23.465039 89671 processor.cc:42] [mainboard]processor_tid: 89671
[common ]  I0807 13:45:23.465281 89672 processor.cc:42] [mainboard]processor_tid: 89672
[common ]  I0807 13:45:23.465423 89673 processor.cc:42] [mainboard]processor_tid: 89673
[common ]  I0807 13:45:23.465840 89674 processor.cc:42] [mainboard]processor_tid: 89674
[common ]  I0807 13:45:23.466204 89675 processor.cc:42] [mainboard]processor_tid: 89675
[common ]  I0807 13:45:23.466418 89676 processor.cc:42] [mainboard]processor_tid: 89676
[common ]  I0807 13:45:23.466558 89677 processor.cc:42] [mainboard]processor_tid: 89677
[common ]  I0807 13:45:23.466643 89678 processor.cc:42] [mainboard]processor_tid: 89678
[common ]  I0807 13:45:23.466754 89679 processor.cc:42] [mainboard]processor_tid: 89679
[common ]  I0807 13:45:23.466890 89680 processor.cc:42] [mainboard]processor_tid: 89680
[common ]  I0807 13:45:23.467018 89681 processor.cc:42] [mainboard]processor_tid: 89681
[common ]  I0807 13:45:23.468291 89682 processor.cc:42] [mainboard]processor_tid: 89682
[common ]  I0807 13:45:23.469774 89683 processor.cc:42] [mainboard]processor_tid: 89683
[common ]  I0807 13:45:23.469964 89684 processor.cc:42] [mainboard]processor_tid: 89684
[common ]  I0807 13:45:23.470100 89685 processor.cc:42] [mainboard]processor_tid: 89685
[common ]  I0807 13:45:23.470238 89686 processor.cc:42] [mainboard]processor_tid: 89686
[common ]  I0807 13:45:23.470341 89668 init.cc:113] [mainboard]Register exit handle succ.
[common ]  E0807 13:45:23.470399 89668 file.cc:76] [mainboard]Failed to open file /apollo/cyber/examples/common_component_example/common.dag in text mode.
[common ]  E0807 13:45:23.470448 89668 file.cc:102] [mainboard]Failed to open file /apollo/cyber/examples/common_component_example/common.dag in binary mode.
[common ]  I0807 13:45:23.470470 89668 module_controller.cc:65] [mainboard]Start initialize dag: /apollo/cyber/examples/common_component_example/common.dag
[common ]  E0807 13:45:23.470476 89668 file.cc:76] [mainboard]Failed to open file /apollo/cyber/examples/common_component_example/common.dag in text mode.
[common ]  E0807 13:45:23.470482 89668 file.cc:102] [mainboard]Failed to open file /apollo/cyber/examples/common_component_example/common.dag in binary mode.
[common ]  E0807 13:45:23.470485 89668 module_controller.cc:119] [mainboard]Get proto failed, file: /apollo/cyber/examples/common_component_example/common.dag
[common ]  E0807 13:45:23.470489 89668 module_controller.cc:67] [mainboard]Failed to load module: /apollo/cyber/examples/common_component_example/common.dag
[common ]  E0807 13:45:23.470527 89668 mainboard.cc:39] [mainboard]module start error.
[common ]  
[cyber_launch_89667] ERROR Process [common] has died [pid 89668, exit code 255, cmd mainboard -d /apollo/cyber/examples/common_component_example/common.dag -p common -s CYBER_DEFAULT].
[cyber_launch_89667] INFO All processes has died.
[cyber_launch_89667] INFO Cyber exit.
[cyber_launch_89667] INFO All processes have been stopped.
dev@dev-virtual-machine:~/work/CyberRT-8.0.0/build$ `

**Comment by minhanghuang** [comment]
> 新的报错 谢谢 `dev@dev-virtual-machine:~/work/CyberRT-8.0.0/build$ source ../install/setup.bash
> 
> dev@dev-virtual-machine:~/work/CyberRT-8.0.0/build$ source setup.bash
> 
> dev@dev-virtual-machine:~/work/CyberRT-8.0.0/build$ cyber_launch start share/examples/common.launch [cyber_launch_89667] INFO Launch file [/home/dev/work/CyberRT-8.0.0/build/share/examples/common.launch] [cyber_launch_89667] INFO ======================================================================================================================== [cyber_launch_89667] INFO Load module [common] library: [common] [CYBER_DEFAULT] conf: [/apollo/cyber/examples/common_component_example/common.dag] exception_handler: [] [cyber_launch_89667] INFO Start process [common] successfully. pid: 89668 [cyber_launch_89667] INFO ------------------------------------------------------------------------------------------------------------------------ [common ] WARNING: Logging before InitGoogleLogging() is written to STDERR [common ] I0807 13:45:23.455677 89668 class_loader_utility.h:79] []registerclass:Circle,Base, [common ] I0807 13:45:23.456017 89668 class_loader_utility.h:79] []registerclass:Rect,Base, [common ] I0807 13:45:23.456054 89668 class_loader_utility.h:79] []registerclass:Triangle,Base, [common ] I0807 13:45:23.456099 89668 class_loader_utility.h:79] []registerclass:Star,Base, [common ] I0807 13:45:23.456108 89668 class_loader_utility.h:79] []registerclass:Apple,Base, [common ] I0807 13:45:23.456115 89668 class_loader_utility.h:79] []registerclass:Pear,Base, [common ] I0807 13:45:23.456120 89668 class_loader_utility.h:79] []registerclass:Banana,Base, [common ] I0807 13:45:23.456130 89668 class_loader_utility.h:79] []registerclass:Peach,Base, [common ] I0807 13:45:23.456626 89668 module_argument.cc:81] []command: mainboard -d /apollo/cyber/examples/common_component_example/common.dag -p common -s CYBER_DEFAULT [common ] I0807 13:45:23.456874 89668 global_data.cc:153] []host ip: 192.168.92.133 [common ] I0807 13:45:23.463938 89668 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is common, has 1 dag conf [common ] I0807 13:45:23.463974 89668 module_argument.cc:60] []dag_conf: /apollo/cyber/examples/common_component_example/common.dag [common ] W0807 13:45:23.464294 89668 scheduler_factory.cc:63] [mainboard]Scheduler conf named /home/dev/work/CyberRT-8.0.0/build/share/conf/common.conf not found, use default. [common ] I0807 13:45:23.465039 89671 processor.cc:42] [mainboard]processor_tid: 89671 [common ] I0807 13:45:23.465281 89672 processor.cc:42] [mainboard]processor_tid: 89672 [common ] I0807 13:45:23.465423 89673 processor.cc:42] [mainboard]processor_tid: 89673 [common ] I0807 13:45:23.465840 89674 processor.cc:42] [mainboard]processor_tid: 89674 [common ] I0807 13:45:23.466204 89675 processor.cc:42] [mainboard]processor_tid: 89675 [common ] I0807 13:45:23.466418 89676 processor.cc:42] [mainboard]processor_tid: 89676 [common ] I0807 13:45:23.466558 89677 processor.cc:42] [mainboard]processor_tid: 89677 [common ] I0807 13:45:23.466643 89678 processor.cc:42] [mainboard]processor_tid: 89678 [common ] I0807 13:45:23.466754 89679 processor.cc:42] [mainboard]processor_tid: 89679 [common ] I0807 13:45:23.466890 89680 processor.cc:42] [mainboard]processor_tid: 89680 [common ] I0807 13:45:23.467018 89681 processor.cc:42] [mainboard]processor_tid: 89681 [common ] I0807 13:45:23.468291 89682 processor.cc:42] [mainboard]processor_tid: 89682 [common ] I0807 13:45:23.469774 89683 processor.cc:42] [mainboard]processor_tid: 89683 [common ] I0807 13:45:23.469964 89684 processor.cc:42] [mainboard]processor_tid: 89684 [common ] I0807 13:45:23.470100 89685 processor.cc:42] [mainboard]processor_tid: 89685 [common ] I0807 13:45:23.470238 89686 processor.cc:42] [mainboard]processor_tid: 89686 [common ] I0807 13:45:23.470341 89668 init.cc:113] [mainboard]Register exit handle succ. **[common ] E0807 13:45:23.470399 89668 file.cc:76] [mainboard]Failed to open file /apollo/cyber/examples/common_component_example/common.dag in text mode.** **[common ] E0807 13:45:23.470448 89668 file.cc:102] [mainboard]Failed to open file /apollo/cyber/examples/common_component_example/common.dag in binary mode. [common ] I0807 13:45:23.470470 89668 module_controller.cc:65] [mainboard]Start initialize dag: /apollo/cyber/examples/common_component_example/common.dag [common ] E0807 13:45:23.470476 89668 file.cc:76] [mainboard]Failed to open file /apollo/cyber/examples/common_component_example/common.dag in text mode. [common ] E0807 13:45:23.470482 89668 file.cc:102] [mainboard]Failed to open file /apollo/cyber/examples/common_component_example/common.dag in binary mode. [common ] E0807 13:45:23.470485 89668 module_controller.cc:119] [mainboard]Get proto failed, file: /apollo/cyber/examples/common_component_example/common.dag [common ] E0807 13:45:23.470489 89668 module_controller.cc:67] [mainboard]Failed to load module: /apollo/cyber/examples/common_component_example/common.dag [common ] E0807 13:45:23.470527 89668 mainboard.cc:39] [mainboard]module start error. [common ]** [cyber_launch_89667] ERROR Process [common] has died [pid 89668, exit code 255, cmd mainboard -d /apollo/cyber/examples/common_component_example/common.dag -p common -s CYBER_DEFAULT]. [cyber_launch_89667] INFO All processes has died. [cyber_launch_89667] INFO Cyber exit. [cyber_launch_89667] INFO All processes have been stopped.
> 
> dev@dev-virtual-machine:~/work/CyberRT-8.0.0/build$ `

@freekevinCode 问题已修复,  examples launch的路径有变化, `cyber_launch start share/examples/common_component_example/common.launch` 注意将`common.launch`和`common.bag`文件中的路径改成自己机器上的路径

**Comment by freekevinCode** [comment]
good job

**Comment by zhoufuch** [comment]
![截图 2023-10-07 13-51-53](https://github.com/minhanghuang/CyberRT/assets/7277305/2af109d6-c9ed-4d6a-b9b2-e82cd0fb80ea)

**Comment by minhanghuang** [comment]
> ![截图 2023-10-07 13-51-53](https://user-images.githubusercontent.com/7277305/273366392-2af109d6-c9ed-4d6a-b9b2-e82cd0fb80ea.png)

感觉是权限的问题, glog创建日志文件失败
