### ISSUE TITLE
BUILD文件怎么添加cyber依赖

### ISSUE THREAD

**Issue by 1121085292** [minhanghuang/CyberRT#44]
cc_library(
    name = "lidar_detection_component",
    srcs = ["lidar_detection_component.cc"],
    hdrs = ["lidar_detection_component.h"],
    deps = [
        "//cyber",
        "//modules/common/util:util_tool",
        "//modules/perception/common/sensor_manager",
        "//modules/perception/lib/registerer",
        "//modules/perception/lidar/app:lidar_obstacle_detection",
        "//modules/perception/lidar/common",
        "//modules/perception/lidar/lib/detector/cnn_segmentation:cnn_segmentation",
        "//modules/perception/lidar/lib/detector/ncut_segmentation:ncut_segmentation",
        "//modules/perception/lidar/lib/detector/point_pillars_detection:point_pillars_detection",
        "//modules/perception/lidar/lib/ground_detector/spatio_temporal_ground_detector",
        "//modules/perception/lidar/lib/interface",
        "//modules/perception/lidar/lib/object_builder",
        "//modules/perception/lidar/lib/object_filter_bank/roi_boundary_filter",
        "//modules/perception/lidar/lib/roi_filter/hdmap_roi_filter",
        "//modules/perception/lidar/lib/scene_manager/ground_service",
        "//modules/perception/lidar/lib/scene_manager/roi_service",
        "//modules/perception/onboard/common_flags",
        "//modules/perception/onboard/inner_component_messages:lidar_inner_component_messages",
        "//modules/perception/onboard/proto:lidar_component_config_cc_proto",
        "//modules/perception/onboard/transform_wrapper",
        "@eigen",
    ],
    alwayslink = True,
在apollo源码中deps直接添加//cyber即可，您使用cmake构建的需要添加什么路径才能依赖cyber呢

**Comment by minhanghuang** [comment]
> cc_library( name = "lidar_detection_component", srcs = ["lidar_detection_component.cc"], hdrs = ["lidar_detection_component.h"], deps = [ "//cyber", "//modules/common/util:util_tool", "//modules/perception/common/sensor_manager", "//modules/perception/lib/registerer", "//modules/perception/lidar/app:lidar_obstacle_detection", "//modules/perception/lidar/common", "//modules/perception/lidar/lib/detector/cnn_segmentation:cnn_segmentation", "//modules/perception/lidar/lib/detector/ncut_segmentation:ncut_segmentation", "//modules/perception/lidar/lib/detector/point_pillars_detection:point_pillars_detection", "//modules/perception/lidar/lib/ground_detector/spatio_temporal_ground_detector", "//modules/perception/lidar/lib/interface", "//modules/perception/lidar/lib/object_builder", "//modules/perception/lidar/lib/object_filter_bank/roi_boundary_filter", "//modules/perception/lidar/lib/roi_filter/hdmap_roi_filter", "//modules/perception/lidar/lib/scene_manager/ground_service", "//modules/perception/lidar/lib/scene_manager/roi_service", "//modules/perception/onboard/common_flags", "//modules/perception/onboard/inner_component_messages:lidar_inner_component_messages", "//modules/perception/onboard/proto:lidar_component_config_cc_proto", "//modules/perception/onboard/transform_wrapper", "@eigen", ], alwayslink = True, 在apollo源码中deps直接添加//cyber即可，您使用cmake构建的需要添加什么路径才能依赖cyber呢

Hi, @1121085292 安装完成后,  通过连接`cyber`, 使用`cyber`
```
find_package(PkgConfig REQUIRED)
pkg_check_modules(Cyber REQUIRED cyber)
include_directories(
  ${Cyber_INCLUDE_DIRS}
)
link_directories(${Cyber_LIB_DIRS})
target_link_libraries(${TARGET_NAME}
  ${Cyber_LIBRARIES}
)
```

**Comment by 1121085292** [comment]
我想沿用bazel,在BUILD文件里可以deps Cyber 吗？

**Comment by minhanghuang** [comment]
> 我想沿用bazel,在BUILD文件里可以deps Cyber 吗？

本仓库保留了bazel的配置文件, 但是没有使用bazel编译过
