### ISSUE TITLE
libfastrtps.so.1.5.0 文件太大,是 debug版本的么?

### ISSUE THREAD

**Issue by 171930433** [minhanghuang/CyberRT#45]
ast-rtps-1.5.0-1.prebuilt.aarch64.tar.gz 
![image](https://github.com/minhanghuang/CyberRT/assets/32025811/c474bfd3-828c-4dd5-858d-59d65806c3de)
看起来是个debug版本的文件,大小将近38m
![image](https://github.com/minhanghuang/CyberRT/assets/32025811/eb040d7f-8514-4dc9-b4d5-47aec36dfb3b)

**Comment by minhanghuang** [comment]
@171930433  仓库中的dds是从Apollo平台下载的编译好的包, 从截图中看是debug版本, 可以使用源码编译release版本的包[把注释打开, 先编译submodule, 在编译dds](https://github.com/minhanghuang/CyberRT/blob/e910802bd5bde8a758b1f6949010ed5b0bb66d99/scripts/install.sh#L68)

**Comment by 171930433** [comment]
./libfastrtps.so.1.5.0: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=7186ecd569a3b6db03d61ea8fc247a9a232e24cc, with debug_info, not stripped
![1706514873619](https://github.com/minhanghuang/CyberRT/assets/32025811/ee52d960-2958-495e-b620-7b798be1b888)


很奇怪，这样编译出来是ReleaseWithDebugInfo，不知道作者是否编译出Release版本

**Comment by minhanghuang** [comment]
> ./libfastrtps.so.1.5.0: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=7186ecd569a3b6db03d61ea8fc247a9a232e24cc, with debug_info, not stripped ![1706514873619](https://private-user-images.githubusercontent.com/32025811/300373699-ee52d960-2958-495e-b620-7b798be1b888.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTUxMjgsIm5iZiI6MTcwNjY5NDgyOCwicGF0aCI6Ii8zMjAyNTgxMS8zMDAzNzM2OTktZWU1MmQ5NjAtMjk1OC00OTVlLWI2MjAtN2I3OThiZTFiODg4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA5NTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NTRjZDU2M2I2ODlkYzc2MTFmODQ3NWRkODQ4MDQzYjA0NjdhNzEyMTM5MGYwYTA3ZWMwN2ZjYjc4MDBhNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u-Io9YRyS_EgSVrr6bR79zhYKgSJT2UXWZ-7olG7IAM)
> 
> 很奇怪，这样编译出来是ReleaseWithDebugInfo，不知道作者是否编译出Release版本

![image](https://github.com/minhanghuang/CyberRT/assets/37317982/efe66322-df9d-441e-93d4-ef9eef9c4912)

我使用源码编译, x86环境, 可以编译出release版本

**Comment by freekevinCode** [comment]
有专门release的脚本，看一下apollo.sh的usage

| |
商文科
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月31日 18:00 |
| 收件人 | minhanghuang/CyberRT ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [minhanghuang/CyberRT] libfastrtps.so.1.5.0 文件太大,是 debug版本的么? (Issue #45) |

./libfastrtps.so.1.5.0: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=7186ecd569a3b6db03d61ea8fc247a9a232e24cc, with debug_info, not stripped

很奇怪，这样编译出来是ReleaseWithDebugInfo，不知道作者是否编译出Release版本

image.png (view on web)

我使用源码编译, x86环境, 可以编译出release版本

**Comment by 171930433** [comment]
我是在windows11的wsl2 ubuntu2204环境中编译的,任然只能编译出 ReleaseWithDebugInfo版本, 但是CMAKE_CACHE文件中查看编译选项的确是release
![image](https://github.com/minhanghuang/CyberRT/assets/32025811/f3d292ab-2e42-47e2-aaba-592f429395c2)
另外,我看编译脚本中,这两个只是安装目录不一致,不过用上面的能编译通过,用下面的编译通不过

**Comment by 171930433** [comment]
> 有专门release的脚本，看一下apollo.sh的usage | | 商文科 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年01月31日 18:00 | | 收件人 | minhanghuang/CyberRT ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | Re: [minhanghuang/CyberRT] libfastrtps.so.1.5.0 文件太大,是 debug版本的么? (Issue #45) | ./libfastrtps.so.1.5.0: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=7186ecd569a3b6db03d61ea8fc247a9a232e24cc, with debug_info, not stripped 很奇怪，这样编译出来是ReleaseWithDebugInfo，不知道作者是否编译出Release版本 image.png (view on web) 我使用源码编译, x86环境, 可以编译出release版本 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

你好,apollo默认用的bazel 编译,这个不是很熟悉怎么看他的编译选项

**Comment by minhanghuang** [comment]
@171930433 非常抱歉, 重新按脚本流程走之后发现, 这是[补丁文件](https://github.com/minhanghuang/CyberRT/blob/e910802bd5bde8a758b1f6949010ed5b0bb66d99/scripts/FastRTPS_1.5.0.patch#L9)的原因导致编出来的库总是debug版本, 解决办法是将补丁文件中的`diff --git a/cmake/dev/check_configuration.cmake b/cmake/dev/check_configuration.cmake`补丁内容删除, 但是这个补丁文件是从[Apollo仓库](https://github.com/ApolloAuto/apollo/blob/r5.5.0/docker/build/installers/FastRTPS_1.5.0.patch)拷贝下来的, 目前不太清楚Apollo为什么要将dds设置成debug模式

**Comment by 171930433** [comment]
> @171930433 非常抱歉, 重新按脚本流程走之后发现, 这是[补丁文件](https://github.com/minhanghuang/CyberRT/blob/e910802bd5bde8a758b1f6949010ed5b0bb66d99/scripts/FastRTPS_1.5.0.patch#L9)的原因导致编出来的库总是debug版本, 解决办法是将补丁文件中的`diff --git a/cmake/dev/check_configuration.cmake b/cmake/dev/check_configuration.cmake`补丁内容删除, 但是这个补丁文件是从[Apollo仓库](https://github.com/ApolloAuto/apollo/blob/r5.5.0/docker/build/installers/FastRTPS_1.5.0.patch)拷贝下来的, 目前不太清楚Apollo为什么要将dds设置成debug模式

![image](https://github.com/minhanghuang/CyberRT/assets/32025811/91e0f09d-cc0b-4fb0-8723-5107a7b1ab1c)
问题解决,多谢

**Comment by 171930433** [comment]
scripts/FastRTPS_1.5.0.patch , patch文件默认添加了    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g") 选项; 关闭即可
