### ISSUE TITLE
package无法通过

### ISSUE THREAD

**Issue by XQSwx** [minhanghuang/CyberRT#49]
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: cyber
CPack: - Install project: cyber
CMake Error at /home/andy/CyberRT/build/cyber/tools/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/home/andy/CyberRT/build/bin/cyber/tools/cyber_service/cyber_monitor".
Call Stack (most recent call first):
  /home/andy/CyberRT/build/cmake_install.cmake:118 (include)

CPack Error: Error when generating package: cyber
Makefile:85: recipe for target 'package' failed
make: *** [package] Error 1

**Comment by minhanghuang** [comment]
@XQSwx 感谢您提供案例, 问题已修复.
