### ISSUE TITLE
v9.0.0版本编译无法通过

### ISSUE THREAD

**Issue by wawozhu** [minhanghuang/CyberRT#51]
我按照README的操作步骤，最后编译报错如下，请问大佬这个是什么导致的呢，protobuf版本是3.14.0

error: ‘class apollo::cyber::proto::Header’ has no member named ‘ByteSizeLong’; did you mean ‘ByteSize’?
   if (static_cast<int64_t>(message->ByteSizeLong()) != size) {
                            ~~~~~~~~~^~~~~~~~~~~~
                            ByteSize
/home/xiangdong/CyberRT/cyber/record/file/record_file_reader.h:86:64: error: ‘class apollo::cyber::proto::Header’ has no member named ‘ByteSizeLong’; did you mean ‘ByteSize’?
            << ", expect: " << size << ", actual: " << message->ByteSizeLong();
                                                       ~~~~~~~~~^~~~~~~~~~~~
                                                       ByteSize

**Comment by minhanghuang** [comment]
Hi @wawozhu, 按顺序执行下面这几行命令确认一下版本
```shell
cd CyberRT
source install/setup.bash
protoc --version
```

如果`protoc --version`的输出是`libprotoc 3.14.0`, 进入`build`进行编译

**Comment by wawozhu** [comment]
大佬好，切换了protoc版本后，上面的报错解决了，但是有下面新的报错，感觉还是protobuf版本的问题呢？

../../libcyber.so：对‘google::protobuf::internal::InlineGreedyStringParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*)’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::AddDescriptors(google::protobuf::internal::DescriptorTable const*)’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::ArenaStringPtr::ClearToEmpty()’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::NonEmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, google::protobuf::Arena*)’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))’未定义的引用
../../libcyber.so：对‘google::protobuf::Any::_InternalParse(char const*, google::protobuf::internal::ParseContext*)’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::GenericSwap(google::protobuf::Message*, google::protobuf::Message*)’未定义的引用
../../libcyber.so：对‘google::protobuf::RepeatedField<float>::data() const’未定义的引用
../../libcyber.so：对‘google::protobuf::RepeatedField<double>::Add(double const&)’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::WireFormat::InternalSerializeUnknownFieldsToArray(google::protobuf::UnknownFieldSet const&, unsigned char*, google::protobuf::io::EpsCopyOutputStream*)’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::EpsCopyInputStream::ReadStringFallback(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::NonEmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::UnknownFieldParse(unsigned long, google::protobuf::UnknownFieldSet*, char const*, google::protobuf::internal::ParseContext*)’未定义的引用
../../libcyber.so：对‘google::protobuf::FileDescriptorProto::FileDescriptorProto(google::protobuf::Arena*)’未定义的引用
../../libcyber.so：对‘google::protobuf::RepeatedField<double>::data() const’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::EpsCopyInputStream::DoneFallback(int, int)’未定义的引用
../../libcyber.so：对‘google::protobuf::Any::ByteSizeLong() const’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::DestroyMessage(void const*)’未定义的引用
../../libcyber.so：对‘google::protobuf::RepeatedField<int>::Clear()’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::ArenaStringPtr::Destroy(google::protobuf::internal::ArenaStringPtr::EmptyDefault, google::protobuf::Arena*)’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const*, bool)’未定义的引用
../../libcyber.so：对‘google::protobuf::_Any_default_instance_’未定义的引用
../../libcyber.so：对‘google::protobuf::FileDescriptor::dependency(int) const’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::ArenaStringPtr::Mutable[abi:cxx11](google::protobuf::internal::ArenaStringPtr::EmptyDefault, google::protobuf::Arena*)’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::kGlobalEmptyTable’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::ArenaImpl::SpaceAllocated() const’未定义的引用
../../libcyber.so：对‘google::protobuf::RepeatedField<double>::MergeFrom(google::protobuf::RepeatedField<double> const&)’未定义的引用
../../libcyber.so：对‘google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RepeatedPtrField(google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&)’未定义的引用
../../libcyber.so：对‘google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RepeatedPtrField(google::protobuf::Arena*)’未定义的引用
../../libcyber.so：对‘google::protobuf::Arena::AllocateAlignedNoHook(unsigned long)’未定义的引用
../../libcyber.so：对‘google::protobuf::Message::SpaceUsedLong() const’未定义的引用
../../libcyber.so：对‘google::protobuf::RepeatedField<int>::~RepeatedField()’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::PackedFloatParser(void*, char const*, google::protobuf::internal::ParseContext*)’未定义的引用
../../libcyber.so：对‘google::protobuf::RepeatedField<float>::size() const’未定义的引用
../../libcyber.so：对‘google::protobuf::Any::_InternalSerialize(unsigned char*, google::protobuf::io::EpsCopyOutputStream*) const’未定义的引用
../../libcyber.so：对‘google::protobuf::RepeatedField<float>::MergeFrom(google::protobuf::RepeatedField<float> const&)’未定义的引用
../../libcyber.so：对‘google::protobuf::internal::fixed_address_empty_string’未定义的引用
../../libcyber.so：对‘google::protobuf::RepeatedField<double>::RepeatedField(google::protobuf::RepeatedField<double> const&)’未定义的引用
collect2: error: ld returned 1 exit status
cyber/tools/CMakeFiles/cyber_recorder.dir/build.make:246: recipe for target 'bin/cyber/tools/cyber_recorder/cyber_recorder' failed
make[2]: *** [bin/cyber/tools/cyber_recorder/cyber_recorder] Error 1
CMakeFiles/Makefile2:639: recipe for target 'cyber/tools/CMakeFiles/cyber_recorder.dir/all' failed
make[1]: *** [cyber/tools/CMakeFiles/cyber_recorder.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by minhanghuang** [comment]
在编译前, 如果是新开的Terminal, 需要加载环境`source install/setup.bash`, 然后才能执行make

**Comment by wawozhu** [comment]
你好，这步是执行过的。

**Comment by minhanghuang** [comment]
非常抱歉, 是最近一次更新的脚本出了问题, 我改一下, 稍等

**Comment by wawozhu** [comment]
好的大佬，看了一下install.py 安装protobuf的地方写成了glog，另外是不是还缺一些依赖啊？

**Comment by minhanghuang** [comment]
> 好的大佬，看了一下install.py 安装protobuf的地方写成了glog，另外是不是还缺一些依赖啊？

可以先使用下面的脚本安装依赖, 取代`install.py`

```shell
cd CyberRT
sudo ./scripts/install.sh
```

**Comment by wawozhu** [comment]
这样ok了大佬，还有一个问题大佬，我现在想用交叉编译器编译这这个工程放个工程放到arm芯片上跑，需要修改哪些地方呢，谢谢。

**Comment by minhanghuang** [comment]
这个工程当前没有交叉编译, 你可以写一个toolchain, arm和amd只需要区分[croutine](https://github.com/minhanghuang/CyberRT/tree/v9.0.0/cyber/croutine/detail)这两个汇编文件就可以

**Comment by wawozhu** [comment]
好的，谢谢大佬～
