### ISSUE TITLE
cyber_launch start share/examples/common_component_example/common.launch时整个节点挂了

### ISSUE THREAD

**Issue by mtht** [minhanghuang/CyberRT#58]
请教一个component测试的问题，编译完成后按Examples的指导测试component, 节点没有成功启动会挂掉，下面是终端的打印

:~/cyber_learn/CyberRT/build$ cyber_launch start share/examples/common_component_example/common.launch
[cyber_launch_6919] INFO Launch file [share/examples/common_component_example/common.launch]
[cyber_launch_6919] INFO ========================================================================================================================
[cyber_launch_6919] INFO Load module [common] library: [common] [CYBER_DEFAULT] conf, exception_handler: [], respawn_limit: [3]
[cyber_launch_6919] INFO Start process [common] successfully. pid: 6920
[cyber_launch_6919] INFO ------------------------------------------------------------------------------------------------------------------------
[common ]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[common ]  I0420 10:14:56.847668  6920 class_loader_utility.h:79] []registerclass:Circle,Base,
[common ]  I0420 10:14:56.848342  6920 class_loader_utility.h:79] []registerclass:Rect,Base,
[common ]  I0420 10:14:56.848472  6920 class_loader_utility.h:79] []registerclass:Triangle,Base,
[common ]  I0420 10:14:56.848591  6920 class_loader_utility.h:79] []registerclass:Star,Base,
[common ]  I0420 10:14:56.848707  6920 class_loader_utility.h:79] []registerclass:Apple,Base,
[common ]  I0420 10:14:56.848821  6920 class_loader_utility.h:79] []registerclass:Pear,Base,
[common ]  I0420 10:14:56.848937  6920 class_loader_utility.h:79] []registerclass:Banana,Base,
[common ]  I0420 10:14:56.849049  6920 class_loader_utility.h:79] []registerclass:Peach,Base,
[common ]  I0420 10:14:56.849503  6920 module_argument.cc:89] []command: mainboard -d /apollo/cyber/examples/common_component_example/common.dag -p common -s CYBER_DEFAULT 

[common ]  I0420 10:14:56.854876  6920 module_argument.cc:62] []binary_name_ is mainboard, process_group_ is common, has 1 dag conf
[common ]  I0420 10:14:56.855017  6920 module_argument.cc:65] []dag_conf: /apollo/cyber/examples/common_component_example/common.dag
[common ]  W0420 10:14:56.855338  6920 scheduler_factory.cc:63] [mainboard]Scheduler conf named /home/ubuntu/cyber_learn/CyberRT/build/share/conf/common.conf not found, use default.
[common ]  I0420 10:14:56.859762  6923 processor.cc:42] [mainboard]processor_tid: 6923
[common ]  I0420 10:14:56.863692  6924 processor.cc:42] [mainboard]processor_tid: 6924
[common ]  I0420 10:14:56.872337  6925 processor.cc:42] [mainboard]processor_tid: 6925
[common ]  I0420 10:14:56.878350  6926 processor.cc:42] [mainboard]processor_tid: 6926
[common ]  I0420 10:14:56.882093  6927 processor.cc:42] [mainboard]processor_tid: 6927
[common ]  I0420 10:14:56.885461  6928 processor.cc:42] [mainboard]processor_tid: 6928
[common ]  I0420 10:14:56.888828  6929 processor.cc:42] [mainboard]processor_tid: 6929
[common ]  I0420 10:14:56.893311  6930 processor.cc:42] [mainboard]processor_tid: 6930
[common ]  I0420 10:14:56.896677  6931 processor.cc:42] [mainboard]processor_tid: 6931
[common ]  I0420 10:14:56.903344  6932 processor.cc:42] [mainboard]processor_tid: 6932
[common ]  I0420 10:14:56.907927  6933 processor.cc:42] [mainboard]processor_tid: 6933
[common ]  I0420 10:14:56.914119  6934 processor.cc:42] [mainboard]processor_tid: 6934
[common ]  I0420 10:14:56.918633  6935 processor.cc:42] [mainboard]processor_tid: 6935
[common ]  I0420 10:14:56.922663  6936 processor.cc:42] [mainboard]processor_tid: 6936
[common ]  I0420 10:14:56.926479  6937 processor.cc:42] [mainboard]processor_tid: 6937
[common ]  I0420 10:14:56.934139  6938 processor.cc:42] [mainboard]processor_tid: 6938
[common ]  I0420 10:14:56.934491  6920 init.cc:113] [mainboard]Register exit handle succ.
[common ]  W0420 10:14:56.934613  6920 environment.h:33] [mainboard]Environment variable [APOLLO_PLUGIN_SEARCH_IN_BAZEL_OUTPUT] not set, fallback to 
[common ]  W0420 10:14:56.934713  6920 environment.h:33] [mainboard]Environment variable [APOLLO_PLUGIN_INDEX_PATH] not set, fallback to 
[common ]  W0420 10:14:56.934803  6920 environment.h:33] [mainboard]Environment variable [APOLLO_DISTRIBUTION_HOME] not set, fallback to 
[common ]  I0420 10:14:56.934890  6920 plugin_manager.cc:177] [mainboard]loading plugins from APOLLO_PLUGIN_INDEX_PATH[]
[common ]  W0420 10:14:56.934970  6920 plugin_manager.cc:188] [mainboard]plugin index path[] not exists
[common ]  E0420 10:14:56.935083  6920 module_controller.cc:55] [mainboard]no dag conf [/apollo/cyber/examples/common_component_example/common.dag] found!
[common ]  E0420 10:14:56.935410  6920 mainboard.cc:39] [mainboard]module start error.
[common ]  
[cyber_launch_6919] ERROR Process [common] has died [pid 6920, exit code 255, cmd mainboard -d /apollo/cyber/examples/common_component_example/common.dag -p common -s CYBER_DEFAULT].
[cyber_launch_6919] INFO All processes has died.
[cyber_launch_6919] INFO Cyber exit.
[cyber_launch_6919] INFO All processes have been stopped.
:~/cyber_learn/CyberRT/build$ 

1.终端提示/home/ubuntu/cyber_learn/CyberRT/build/share/conf/common.conf not found， 去share/conf/路径下检查确实没有common.conf
2.然后提示几个环境设置问题Environment variable [APOLLO_PLUGIN_SEARCH_IN_BAZEL_OUTPUT] not set, fallback to， 节点就退出了

**Comment by minhanghuang** [comment]
Hi, @mtht  这个问题我在本地复现, 具体需要修改两个地方:
- 第一个是运行时指定的common.launch文件(`share/examples/common_component_example/common.launch`)
- 第二个是CMakeLists.txt, 具体参考这里: [CMakeLists](https://github.com/minhanghuang/CyberRT/pull/59/files)

**Comment by mtht** [comment]
hello, @minhanghuang, 感谢您百忙之中抽时间查看，按您说的方法试了一下，已经能跑了
