### ISSUE TITLE
aarch64有使用过吗，能正常使用talker和listener测试通过吗？

### ISSUE THREAD

**Issue by sundongdong4300** [minhanghuang/CyberRT#76]
我这边测试listener崩溃；
1. 能否提供aarch64编译步骤
2. fast-rtps-1.5.0-1.prebuilt.aarch64.tar.gz工程源码可以给一个吗？

**Comment by minhanghuang** [comment]
> 我这边测试listener崩溃；
> 
> 1. 能否提供aarch64编译步骤
> 2. fast-rtps-1.5.0-1.prebuilt.aarch64.tar.gz工程源码可以给一个吗？

hello @sundongdong4300  

CyberRT编译过程如下:
```shell
cd CyberRT
python3 install.py
source install/setup.bash
mkdir -p build && cd build
cmake .. && make -j$(nproc)
```

`fast-rtps-1.5.0-1.prebuilt.aarch64.tar.gz`这个文件是百度Apollo预编译好的文件, [源码参考这里](https://github.com/eProsima/Fast-DDS/tree/v1.5.0), 需要打补丁, [补丁参考这里](https://github.com/ApolloAuto/apollo-platform/blob/master/ros/third_party/FastRTPS_1.4.0.patch)

**Comment by sundongdong4300** [comment]
感谢，我在试试去

**Comment by sundongdong4300** [comment]
yg@ubuntu:~/project/uav/platform/rk3588/git_release/0926/rk3588_sdk/external/sf/Fast-RTPS$ git branch 
* 1.5.0

yg@ubuntu:~/project/uav/platform/rk3588/git_release/0926/rk3588_sdk/external/sf/Fast-RTPS$ patch -p1 < FastRTPS_1.4.0.patch 
patching file CMakeLists.txt
Hunk #1 FAILED at 175.
1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
patching file include/fastrtps/utils/IPFinder.h
patching file src/cpp/qos/ParameterList.cpp
Hunk #1 succeeded at 402 with fuzz 1 (offset 33 lines).
patching file src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp
Hunk #3 succeeded at 427 (offset 38 lines).
Hunk #4 succeeded at 445 (offset 38 lines).
Hunk #5 succeeded at 462 (offset 38 lines).
Hunk #6 succeeded at 480 (offset 38 lines).
patching file src/cpp/transport/UDPv4Transport.cpp
Hunk #1 succeeded at 30 with fuzz 1 (offset -1 lines).
Hunk #2 succeeded at 210 (offset 41 lines).
patching file thirdparty/fastcdr/CMakeLists.txt
Hunk #1 FAILED at 106.
1 out of 1 hunk FAILED -- saving rejects to file thirdparty/fastcdr/CMakeLists.txt.rej
patching file thirdparty/fastcdr/include/fastcdr/Cdr.h
patching file thirdparty/fastcdr/src/cpp/Cdr.cpp

**Comment by sundongdong4300** [comment]
1.4patch打不进去，你那边有试过吗？

**Comment by minhanghuang** [comment]
> 1.4patch打不进去，你那边有试过吗？

@sundongdong4300 不好意思, 你试一下[1.5patch](https://raw.githubusercontent.com/ApolloAuto/apollo/refs/heads/r5.5.0/docker/build/installers/FastRTPS_1.5.0.patch)

**Comment by sundongdong4300** [comment]
太客气了，我昨天使用1.5打进去了。我想知到你在aarch64测试demo能正常talker发送和listener接收吗？

**Comment by minhanghuang** [comment]
> 太客气了，我昨天使用1.5打进去了。我想知到你在aarch64测试demo能正常talker发送和listener接收吗？

![image](https://github.com/user-attachments/assets/a784e3bd-e0f3-44f1-b816-39413bf7fedc)

我这边使用arrch64可以正常收发。不知道你是报了什么错

**Comment by sundongdong4300** [comment]
厉害。我是移植到rk3588上测试的，因此不能正常通信，稍后我搭建好环境，在发给你看看，有您的帮助，真的万分幸运，感谢！！！

**Comment by sundongdong4300** [comment]
// cyber_example_talker
root@rk3588-buildroot:/# source install/setup.bash 
root@rk3588-buildroot:/# cd build/
root@rk3588-buildroot:/build# source setup.bash 
root@rk3588-buildroot:/build# ./cyber/examples/cyber_example_talker 
I0101 00:01:43.460406  1366 global_data.cc:153] [cyber_example_talker]host ip: 127.0.0.1
W0101 00:01:43.462194  1366 scheduler_factory.cc:63] [cyber_example_talker]Scheduler conf named /build/share/conf/cyber_example_talker_1366.conf not found, use default.
I0101 00:01:43.462632  1368 processor.cc:42] [cyber_example_talker]processor_tid: 1368
I0101 00:01:43.462783  1369 processor.cc:42] [cyber_example_talker]processor_tid: 1369
I0101 00:01:43.462921  1370 processor.cc:42] [cyber_example_talker]processor_tid: 1370
I0101 00:01:43.463022  1371 processor.cc:42] [cyber_example_talker]processor_tid: 1371
I0101 00:01:43.463111  1372 processor.cc:42] [cyber_example_talker]processor_tid: 1372
I0101 00:01:43.463229  1373 processor.cc:42] [cyber_example_talker]processor_tid: 1373
I0101 00:01:43.463280  1374 processor.cc:42] [cyber_example_talker]processor_tid: 1374
I0101 00:01:43.463346  1375 processor.cc:42] [cyber_example_talker]processor_tid: 1375
I0101 00:01:43.463464  1376 processor.cc:42] [cyber_example_talker]processor_tid: 1376
I0101 00:01:43.463516  1377 processor.cc:42] [cyber_example_talker]processor_tid: 1377
I0101 00:01:43.463628  1378 processor.cc:42] [cyber_example_talker]processor_tid: 1378
I0101 00:01:43.463690  1379 processor.cc:42] [cyber_example_talker]processor_tid: 1379
I0101 00:01:43.463797  1380 processor.cc:42] [cyber_example_talker]processor_tid: 1380
I0101 00:01:43.463903  1381 processor.cc:42] [cyber_example_talker]processor_tid: 1381
I0101 00:01:43.463969  1382 processor.cc:42] [cyber_example_talker]processor_tid: 1382
I0101 00:01:43.464016  1383 processor.cc:42] [cyber_example_talker]processor_tid: 1383
I0101 00:01:43.464038  1366 init.cc:113] [cyber_example_talker]Register exit handle succ.
I0101 00:01:43.468896  1366 talker.cc:43] [cyber_example_talker]talker sent a message! No. 0
I0101 00:01:44.469078  1366 talker.cc:43] [cyber_example_talker]talker sent a message! No. 1

// cyber_example_listener
root@rk3588-buildroot:/# source install/setup.bash 
root@rk3588-buildroot:/# cd build/
root@rk3588-buildroot:/build# source setup.bash 
root@rk3588-buildroot:/build# ./cyber/examples/cyber_example_listener 
I0101 00:02:17.371700  1403 global_data.cc:153] [cyber_example_listener]host ip: 127.0.0.1
W0101 00:02:17.373436  1403 scheduler_factory.cc:63] [cyber_example_listener]Scheduler conf named /build/share/conf/cyber_example_listener_1403.conf not found, use default.
I0101 00:02:17.373708  1405 processor.cc:42] [cyber_example_listener]processor_tid: 1405
I0101 00:02:17.373953  1406 processor.cc:42] [cyber_example_listener]processor_tid: 1406
I0101 00:02:17.374037  1407 processor.cc:42] [cyber_example_listener]processor_tid: 1407
I0101 00:02:17.374148  1408 processor.cc:42] [cyber_example_listener]processor_tid: 1408
I0101 00:02:17.374219  1409 processor.cc:42] [cyber_example_listener]processor_tid: 1409
I0101 00:02:17.374279  1410 processor.cc:42] [cyber_example_listener]processor_tid: 1410
I0101 00:02:17.374391  1411 processor.cc:42] [cyber_example_listener]processor_tid: 1411
I0101 00:02:17.374439  1412 processor.cc:42] [cyber_example_listener]processor_tid: 1412
I0101 00:02:17.374494  1413 processor.cc:42] [cyber_example_listener]processor_tid: 1413
I0101 00:02:17.374548  1414 processor.cc:42] [cyber_example_listener]processor_tid: 1414
I0101 00:02:17.374599  1415 processor.cc:42] [cyber_example_listener]processor_tid: 1415
I0101 00:02:17.374656  1416 processor.cc:42] [cyber_example_listener]processor_tid: 1416
I0101 00:02:17.374727  1417 processor.cc:42] [cyber_example_listener]processor_tid: 1417
I0101 00:02:17.374778  1418 processor.cc:42] [cyber_example_listener]processor_tid: 1418
I0101 00:02:17.374843  1419 processor.cc:42] [cyber_example_listener]processor_tid: 1419
I0101 00:02:17.374891  1420 processor.cc:42] [cyber_example_listener]processor_tid: 1420
I0101 00:02:17.374900  1403 init.cc:113] [cyber_example_listener]Register exit handle succ.
I0101 00:02:17.379891  1403 scheduler.cc:55] [cyber_example_listener]create croutine: listener_channel/chatter
Segmentation fault

**Comment by sundongdong4300** [comment]
我这就是现在这现象，直接段错误！！！

**Comment by minhanghuang** [comment]
> 我这就是现在这现象，直接段错误！！！

你在本地是如何编译的, cmake 有加什么编译参数吗,

**Comment by sundongdong4300** [comment]
# source /home/yg/project/uav/platform/rk3588/sdk/aarch64-buildroot-linux-gnu_sdk-buildroot/environment-setup
# python3 install.py
# source install/setup.bash
# mkdir -p build && cd build
# cmake -Dfastcdr_DIR=/home/yg/project/uav/apollo/1030/CyberRT/install/lib/fastcdr/cmake/ -Dfastrtps_DIR=/home/yg/project/uav/apollo/1030/CyberRT/install/lib/fastrtps/cmake/ -DProtobuf_LIBRARIES=protobuf -DProtobuf_INCLUDE_DIR=/home/yg/project/uav/apollo/1030/CyberRT/install/include/ ..
# make -j12

**Comment by sundongdong4300** [comment]
请问您那边aarch64成功是使用的真实机器还是docker环境？

**Comment by minhanghuang** [comment]
> 请问您那边aarch64成功是使用的真实机器还是docker环境？

我用的物理机和docker都可以, 你在编译时添加参数 cmake -DCMAKE_BUILD_TYPE=Debug ..

```shell
cmake -DCMAKE_BUILD_TYPE=Debug -Dfastcdr_DIR=/home/yg/project/uav/apollo/1030/CyberRT/install/lib/fastcdr/cmake/ -Dfastrtps_DIR=/home/yg/project/uav/apollo/1030/CyberRT/install/lib/fastrtps/cmake/ -DProtobuf_LIBRARIES=protobuf -DProtobuf_INCLUDE_DIR=/home/yg/project/uav/apollo/1030/CyberRT/install/include/ ..
```

**Comment by minhanghuang** [comment]
> > 请问您那边aarch64成功是使用的真实机器还是docker环境？
> 
> 我用的物理机和docker都可以, 你在编译时添加参数 `cmake -DCMAKE_BUILD_TYPE=Debug ..`试一试
> 
> ```shell
> cmake -DCMAKE_BUILD_TYPE=Debug -Dfastcdr_DIR=/home/yg/project/uav/apollo/1030/CyberRT/install/lib/fastcdr/cmake/ -Dfastrtps_DIR=/home/yg/project/uav/apollo/1030/CyberRT/install/lib/fastrtps/cmake/ -DProtobuf_LIBRARIES=protobuf -DProtobuf_INCLUDE_DIR=/home/yg/project/uav/apollo/1030/CyberRT/install/include/ ..
> ```

**Comment by minhanghuang** [comment]
> 请问您那边aarch64成功是使用的真实机器还是docker环境？

 我用的物理机和docker都可以, 你在编译时添加参数 `cmake -DCMAKE_BUILD_TYPE=Debug ..`试一试
 ```shell
 cmake -DCMAKE_BUILD_TYPE=Debug -Dfastcdr_DIR=/home/yg/project/uav/apollo/1030/CyberRT/install/lib/fastcdr/cmake/ -Dfastrtps_DIR=/home/yg/project/uav/apollo/1030/CyberRT/install/lib/fastrtps/cmake/ -DProtobuf_LIBRARIES=protobuf -DProtobuf_INCLUDE_DIR=/home/yg/project/uav/apollo/1030/CyberRT/install/include/ ..
 ```

**Comment by i-Nog** [comment]
@sundongdong4300 您好，请问您那边在rk3588物理版上的段错误是怎么解决的。
